Calcs/Models/CalculateBhaskaraViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Calcs.Models
{
    public class CalculateBhaskaraViewModel
    {
        [Display(Name ="Valor A")]
        [Required(ErrorMessage ="O campo do valor A precisa ser preenchido")]
        public double ValueA { get; set; }
        [Display(Name = "Valor B")]
        public double ValueB { get; set; }
        [Display(Name = "Valor C")]
        public double ValueC { get; set; }
        [Display(Name = "Resultado do primeiro X")]
        public double X1 { get; set; }
        [Display(Name = "Resultado do segundo X")]
        public double X2 { get; set; }
    }
}

Calcs/Models/CalculateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Calcs.Models
{
    public class CalculateViewModel
    {
        //primeiro valor
        [Display(Name ="Primeiro valor")]
        public double ValueA { get; set; }
        //segundo valor
        [Display(Name ="Segundo valor")]
        public double ValueB { get; set; }
        //operadores: + : - : * : /
        [Display(Name ="Operador")]
        public string? Operator { get; set; }
        //resultado
        [Display(Name ="Resultado")]
        public double Result { get; set; }
    }
}

Calcs/Models/ErrorViewModel.cs
namespace Calcs.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Calcs/Models/iteratorModel.cs
namespace Calcs.Models
{
    public class iteratorModel
    {
        int[] Numbers = new int[500];
        int[] pairNumbers = new int[250];
        int[] OddNumbers = new int[250];
    }
}

Calcs/Controllers/BhaskaraCalculatorController.cs
using Microsoft.AspNetCore.Mvc;
using Calcs.Models;

namespace Calcs.Controllers
{
    public class BhaskaraCalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(CalculateBhaskaraViewModel data)
        {
            double delta = Math.Pow(data.ValueB, 2) - (4 * data.ValueA * data.ValueC);

            if(delta < 0)
            {
                ViewBag.DeltaZero = "O valor de delta é negativo. A equação nã possui raízes reias";
            }

            data.X1 = (-data.ValueB + Math.Sqrt(delta)) / (2 * data.ValueA);
            data.X2 = (-data.ValueB - Math.Sqrt(delta)) / (2 * data.ValueA);

            return View(data);
        }
    }
}

Calcs/Controllers/CalculatorController.cs
using Calcs.Models;
using Microsoft.AspNetCore.Mvc;

namespace Calcs.Controllers
{
    public class CalculatorController : Controller
    {
        //método Get que irá nos retornar uma view
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        //método post que irá nos retornar o resultado da operação
        [HttpPost]
        public IActionResult Index(CalculateViewModel calculateViewModel)
        {
            ModelState.Clear();
            if ("+".Equals(calculateViewModel.Operator))
            {
                calculateViewModel.Result = calculateViewModel.ValueA + calculateViewModel.ValueB;
            }
            else if ("-".Equals(calculateViewModel.Operator))
            {
                calculateViewModel.Result = calculateViewModel.ValueA - calculateViewModel.ValueB;

            }
            else if ("*".Equals(calculateViewModel.Operator))
            {
                calculateViewModel.Result = calculateViewModel.ValueA * calculateViewModel.ValueB;
            }
            else if ("/".Equals(calculateViewModel.Operator))
            {
                calculateViewModel.Result = calculateViewModel.ValueA / calculateViewModel.ValueB;
            }
            else
            {
                throw new Exception("operador inválido");
            }



            return View(calculateViewModel);
        }
    }
}

Calcs/Controllers/HomeController.cs
using Calcs.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Calcs.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Calcs/Controllers/IteratorController.cs
using Microsoft.AspNetCore.Mvc;

namespace Calcs.Controllers
{
    public class IteratorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Calcs/Views/BhaskaraCalculator/Index.cshtml
@model Calcs.Models.CalculateBhaskaraViewModel

@{
    ViewData["Title"] = "Bhaskara Calculator";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <form asp-action="Index" method="post">
        <label asp-for="ValueA"></label>
        <input asp-for="ValueA" />

        <label asp-for="ValueB"></label>
        <input asp-for="ValueB" />

        <label asp-for="ValueC"></label>
        <input asp-for="ValueC" />

        <input type="submit" value="Calcular" />
        <span asp-validation-for="ValueA" class="text-danger"></span>
    </form>

    <span>@ViewBag.DeltaZero </span>
</div>

<td>@Html.DisplayNameFor(model => model.X1) </td>
<td>@Html.DisplayTextFor(model => model.X1) </td>
<br />
<td>@Html.DisplayNameFor(model => model.X2) </td>
<td>@Html.DisplayTextFor(model => model.X2) </td>



<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Calcs/Views/Calculator/Index.cshtml
@model Calcs.Models.CalculateViewModel

@{
    ViewData["Title"] = "Simple Calculator";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Index" method="post" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ValueA" class="control-label"></label>
                <input asp-for="ValueA" class="form-control" />
                <span asp-validation-for="ValueA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValueB" class="control-label"></label>
                <input asp-for="ValueB" class="form-control" />
                <span asp-validation-for="ValueB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Operator" class="control-label"></label>
                <input asp-for="Operator" class="form-control" />
                <span asp-validation-for="Operator" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="calcular" class="btn btn-primary" />
            </div>
        </form>

    </div>
        <td>@Html.DisplayNameFor(model => model.Result)</td>
        <td>@Html.DisplayTextFor(model => model.Result)</td>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Calcs/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Calcs</h1>
    <p>This a basic project what have basic calculations of math. This is maked just to fix the basic in my head</p>
</div>

<div>
    <h1>Bhaskara</h1>

    <div class="container">


    </div>
</div>

Calcs/Views/Iterator/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Iterator</h1>
<p> Ao clicar no botão será gerado 500 numeros diferentes, os quais serão separados em dois grupos, pares e impares, após eles serem separados
    será feita a soma deles, tanto separados quanto juntos</p>

    <button>

Calcs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Calcs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Calcs.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Calcs</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Index">Calculator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BhaskaraCalculator" asp-action="Index">Bhaskara</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Calcs - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>